name: Code Review Action

on:
  pull_request:
    types: [labeled]

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
    - name: Check label
      run: |
        echo "Another label added: ${{github.event.label.name}}"