name: Code Review Action

on:
  pull_request:
    types: [labeled]

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
    - name: Check label
      if: github.event.label.name == 'code review'
      run: |
        LABEL_DATE=${{ github.event.pull_request.labels }}
        echo "My name is $LABEL_DATE"
    - name: Check for another label
      if: github.event.label.name != 'code review'
      run: |
        echo "Another label added: ${{github.event.label.name}}"
        # Add steps to handle the additional label here