name: Code Review Action

on:
  pull_request:
    types: [labeled]

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
    - name: Check label
      if: github.event.label.name == 'code review'
      run: |
        timeout 1m
        echo "this is label${{github.event.label.name}}"
    - name: Check for another label
      if: github.event.label.name != 'code review'
      run: |
        echo "Another label added: ${{github.event.label.name}}"
        # Add steps to handle the additional label here