 on:
  pull_request_review:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Check label
      if: ${{ contains(github.event.label.name, 'code review') }}
      run: |
        echo "Code review label added"
        # send notification or update status